### ISSUE TITLE
license

### ISSUE THREAD

**Issue by revolunet** [flrent/ConfMate#4]
Hi Florent :)

Great app thanks for sharing. Whats the license terms if we want to use it for a free project ? for a commecial project ?

Thanks

**Comment by flrent** [comment]
Thanks Julien!
License for the moment is just (not really well) detailed on the github pages, but basically free for any non profit event( or open source free event) and it will stay that way. For commercial project, I plan on having a stable version in June, and it won't be free but I will detail it a bit more then. 
I'll keep you in touch!

**Comment by thaeli** [comment]
This is still open. Can you please add a LICENSE file to the repo detailing the exact license this code is under?
